
module.exports.nouns = [
  'factory reset button',
'blood rage',
'idiot',
'toaster',
'legend',
'death wish',
'therapy',
'goal in life',
'marketing idea',
'psychic',
'knife',
'sandwich',
'hunting ground',
'lettuce',
'kitty',
'friendly grandma',
'french chef',
'antidepressant drug',
'corn cake',
'president of the night',
'candlestick maker',
'coffee pot',
'brethren',
'national security agency',
'tank',
'useless brakes',
'international law enforcement agency',
'sound barrier',
'skinny woman',
'private investor',
'main people',
'stock car',
'elastic band',
'whole blood',
'telephone',
'mad cow disease',
'scourge upon the earth',
'rough-skinned newt',
'karate',
'pistol',
'legal warrant',
'people who are hurt',
'idea he suggested',
'party of the first part',
'place of business',
'double fault',
'kitty cat',
'famous landscape painting',
'hairy legs',
'old irish cottage',
'pocket flask',
'liquid oxygen',
'laser beams',
'preventive strike',
'dingle berry',
'reading party',
'generalized bond',
'indirect expression',
'messiness',
'love of her life',
'trust fund',
'volcanic crater',
'travel guidebook',
'electric furnace',
'internal respiration',
'police squad',
'mad-dog skullcap',
'sneaky criminal',
'new version',
'keepsake machete',
'gaming laptop',
'hissy fit',
'dog poop',
'dragon',
'mediation',
'patrolman',
'pervert',
'toilet seat',
'haunted graveyard',
'really tough guy',
'twinkling uncleanness',
'wrinkle',
'personal credit line',
'multi-billionaire',
'mental disorder',
'sweet tailpipe',
'boiling water',
'deer antler',
'background story',
'mood',
'nibblets',
'striped hyena',
'weed wacker'
];
